import { useEffect, useState, type FormEvent } from 'react';
import type { Category } from '../../../../../packages/domain/src/content';
import { sendCommand } from '../../platform/api';
import { useUserCollection } from '../content/useUserCollection';
import { useAuth } from '../identity/AuthProvider';

export function Settings() {
  const { session, refresh } = useAuth(); const { items: categories, error } = useUserCollection<Category>('categories');
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { document.title = 'Preferências · Leve'; }, []);
  async function createCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const fields = new FormData(form); setBusy(true);
    try { await sendCommand({ command: 'category.create', operationId: crypto.randomUUID(), entityId: crypto.randomUUID(), expectedRevision: 0, payload: { name: String(fields.get('name')), colorHex: String(fields.get('color')), sortOrder: categories.length } }); form.reset(); setMessage('Categoria criada.'); } catch (failure) { setMessage(failure instanceof Error ? failure.message : 'Não foi possível criar.'); } finally { setBusy(false); } }
  async function archive(category: Category & { id: string }) { setBusy(true); try { await sendCommand({ command: 'category.archive', operationId: crypto.randomUUID(), entityId: category.id, expectedRevision: category.revision, payload: {} }); } catch (failure) { setMessage(failure instanceof Error ? failure.message : 'Não foi possível arquivar.'); } finally { setBusy(false); } }
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const fields = new FormData(event.currentTarget); setBusy(true); try { await sendCommand({ command: 'profile.update', operationId: crypto.randomUUID(), entityId: session!.uid, expectedRevision: session!.profile!.revision, payload: { displayName: String(fields.get('displayName')), locale: 'pt-BR', timeZone: String(fields.get('timeZone')), weekStartsOn: Number(fields.get('weekStartsOn')), reduceTransparency: fields.get('reduceTransparency') === 'on' } }); await refresh(); setMessage('Preferências salvas.'); } catch (failure) { setMessage(failure instanceof Error ? failure.message : 'Não foi possível salvar.'); } finally { setBusy(false); } }
  return <main><header className="page-heading"><p className="eyebrow">Conta e aparência</p><h1 id="page-title" tabIndex={-1}>Preferências</h1></header><section className="panel content-form"><h2>Perfil</h2><form onSubmit={saveProfile}><label>Nome<input name="displayName" defaultValue={session!.profile!.displayName} required maxLength={80} /></label><label>Fuso horário<input name="timeZone" defaultValue={session!.profile!.timeZone} required /></label><label>Primeiro dia da semana<select name="weekStartsOn" defaultValue={session!.profile!.weekStartsOn}><option value="1">Segunda-feira</option><option value="0">Domingo</option></select></label><label className="check-label"><input type="checkbox" name="reduceTransparency" defaultChecked={session!.profile!.reduceTransparency} /> Reduzir transparência</label><button className="primary" disabled={busy}>Salvar preferências</button></form></section><section className="panel content-form"><h2>Categorias</h2><form onSubmit={createCategory}><label>Nome<input name="name" required maxLength={40} /></label><label>Cor<input name="color" type="color" defaultValue="#86A5C6" /></label><button className="primary" disabled={busy}>Criar categoria</button></form><ul className="settings-list">{categories.filter(item => !item.deletedAt).map(category => <li key={category.id}><span className="color-dot" style={{ background: category.colorHex }} /><strong>{category.name}</strong><button disabled={busy || Boolean(category.archivedAt)} onClick={() => void archive(category)}>{category.archivedAt ? 'Arquivada' : 'Arquivar'}</button></li>)}</ul></section><p role="status">{error || message}</p></main>;
}
