import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { Temporal } from '@js-temporal/polyfill';

test('dia inteiro usa meia-noite e as cores de atividade e nota ficam em modais compactos', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/entrar');
  await page.getByLabel('E-mail').fill('leve.local@example.test');
  await page.getByLabel('Senha', { exact: true }).fill('leve-local-123');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.locator('#page-title')).toHaveText(/Finalize sua agenda|Meu dia/);
  if (await page.getByRole('heading', { name: 'Finalize sua agenda' }).count()) await page.getByRole('button', { name: 'Criar minha agenda' }).click();
  await expect(page.locator('#page-title')).toHaveText('Meu dia');
  const skip = page.getByRole('button', { name: 'Pular guia', exact: true });
  await skip.waitFor({ state: 'visible', timeout: 3000 }).catch(() => undefined);
  if (await skip.isVisible()) await skip.click();
  await page.getByRole('button', { name: 'Nova atividade' }).click();
  await page.getByRole('combobox', { name: 'Tipo', exact: true }).selectOption('event');
  await page.getByLabel('Compromisso de dia inteiro').check();
  const title = `Feira dia inteiro ${Date.now()}`;
  await page.getByLabel('Título', { exact: true }).fill(title);
  const date = Temporal.Now.plainDateISO('America/Sao_Paulo').add({ days: 2 }).toString();
  await page.getByLabel('Início', { exact: true }).fill(date);
  await page.getByLabel('Último dia', { exact: true }).fill(date);
  await page.locator('.activity-composer .optional-fields > summary').click();
  await expect(page.getByLabel('Horário do aviso para dia inteiro')).toHaveValue('00:00');
  const trigger = page.getByRole('button', { name: /Cor da atividade/ });
  await trigger.click();
  let dialog = page.getByRole('dialog', { name: 'Cor da atividade', exact: true });
  await expect(dialog).toBeVisible();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await dialog.getByRole('button', { name: 'Lavanda', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();
  await trigger.click();
  await expect(dialog.getByRole('button', { name: 'Lavanda', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.screenshot({ path: '/tmp/leve-activity-color-modal.png' });
  await page.keyboard.press('Escape');
  await expect(trigger).toBeFocused();
  const saved = page.waitForResponse(response => response.url().endsWith('/api/commands') && response.request().postDataJSON()?.command === 'activity.create');
  await page.getByRole('button', { name: 'Adicionar atividade' }).click();
  const response = await saved;
  expect(response.status()).toBe(200);
  expect(response.request().postDataJSON().payload).toMatchObject({ dayReminderTime: '00:00', colorHex: '#8872B2', schedule: { allDay: true } });

  await page.getByRole('link', { name: 'Notas', exact: true }).click();
  await page.locator('.note-composer .optional-fields > summary').click();
  await page.getByRole('button', { name: /Estilo da nota/ }).click();
  dialog = page.getByRole('dialog', { name: 'Estilo da nota', exact: true });
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: 'Estudos', exact: true }).click();
  await expect(page.locator('.note-composer')).toHaveAttribute('data-note-preset', 'studies');
  const noteTitle = `Nota colorida ${Date.now()}`;
  await page.getByLabel('Título', { exact: true }).fill(noteTitle);
  await page.getByLabel('Texto', { exact: true }).fill('Conteúdo preservado.');
  const noteSaved = page.waitForResponse(result => result.url().endsWith('/api/commands') && result.request().postDataJSON()?.command === 'note.save');
  await page.getByRole('button', { name: 'Salvar nota', exact: true }).click();
  const noteResponse = await noteSaved;
  expect(noteResponse.status()).toBe(200);
  expect(noteResponse.request().postDataJSON().payload.paperColorPreset).toBe('studies');
  await page.reload();
  const note = page.locator('article.note').filter({ hasText: noteTitle });
  await expect(note).toHaveClass(/studies/);
  await note.getByRole('button', { name: 'Editar', exact: true }).click();
  await expect(page.getByLabel('Título', { exact: true })).toBeFocused();
  await page.getByRole('button', { name: /Estilo da nota/ }).click();
  dialog = page.getByRole('dialog', { name: 'Estilo da nota', exact: true });
  await expect(dialog.getByRole('button', { name: 'Estudos', exact: true })).toHaveAttribute('aria-pressed', 'true');
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.screenshot({ path: '/tmp/leve-note-color-modal.png' });
  await page.setViewportSize({ width: 1280, height: 900 });
  await expect(dialog).toBeVisible();
  await page.addStyleTag({ content: 'html { font-size: 200% !important; }' });
  await expect(dialog.getByRole('button', { name: 'Estudos', exact: true })).toBeInViewport();
  await page.keyboard.press('Escape');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
