import { sealedRescheduleFixture } from '../helpers/gikaConfirmation';
import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { Temporal } from '@js-temporal/polyfill';
const dueDate = Temporal.Now.instant().toZonedDateTimeISO('America/Sao_Paulo').toPlainDate().toString();
async function enter(page: Page) {
  await page.goto('/entrar'); await page.getByLabel('E-mail').fill('leve.local@example.test'); await page.getByLabel('Senha', { exact: true }).fill('leve-local-123'); await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.locator('#page-title')).toHaveText(/Finalize sua agenda|Meu dia/);
  if (await page.getByRole('heading', { name: 'Finalize sua agenda' }).count()) await page.getByRole('button', { name: 'Criar minha agenda' }).click();
  await expect(page.locator('#page-title')).toHaveText('Meu dia'); const skip = page.getByRole('button', { name: 'Pular guia', exact: true }); await skip.waitFor({ state: 'visible', timeout: 3000 }).catch(() => undefined);
  if (await skip.isVisible()) { const ack = page.waitForResponse(r => r.url().endsWith('/api/commands') && r.request().postDataJSON()?.command === 'profile.completeTutorial'); await skip.click(); await ack; }
}
const payload = (title: string) => ({ title, descriptionPlain: 'Nota sintética preservada', categoryId: null, colorHex: '#65A885', estimatedMinutes: 35, reminderSpecs: [], schedule: { type: 'task', dueDate, dueTime: null, timeZone: 'America/Sao_Paulo', disambiguation: 'reject' } });
async function create(page: Page, title: string) { return page.evaluate(async value => {
  const path = '/src/platform/api.ts'; const { sendCommand } = await import(/* @vite-ignore */ path); const id = crypto.randomUUID();
  await sendCommand({ command: 'activity.create', operationId: crypto.randomUUID(), entityId: id, expectedRevision: 0, payload: value }); return id;
}, payload(title)); }
const tomorrow=Temporal.PlainDate.from(dueDate).add({days:1}).toString();
const descriptor=(id:string,title:string,time:string|null=null)=>({text:'Confira a nova data antes de mover a tarefa.',simulated:false,reads:[],rescheduleTask:{id,title,dueDate,dueTime:time,timeZone:'America/Sao_Paulo',revision:1,patch:{dueDate:tomorrow}}});
async function ask(page:Page,title:string){await page.getByRole('button',{name:'Pergunte à Gika'}).click();const q=page.getByRole('textbox',{name:'Pergunte à Gika',exact:true});await q.fill(`Move "${title}" para amanhã`);await q.press('Enter');return q;}
for(const mobile of [false,true])test(`M4-T3 ${mobile?'mobile dark':'desktop light'} preview, double tap, structured result after real ack`,async({page})=>{
 if(mobile){await page.setViewportSize({width:390,height:844});await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});}await enter(page);if(mobile)await page.evaluate(async()=>{const path='/src/platform/theme.ts';(await import(/* @vite-ignore */path)).applyAppearance('dark');});
 const title=`Academia M4T3 ${mobile?'mobile':'desktop'}`,id=await create(page,title);await create(page,title+' outro');let model=0,committed=false;const ops:string[]=[];
 await page.route('**/api/gika/respond',async route=>{model++;return route.fulfill({json:await sealedRescheduleFixture(page,route.request().postDataJSON(),descriptor(id,title).rescheduleTask)});});let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});
 await page.route('**/api/commands',async route=>{const c=route.request().postDataJSON();expect(c.command).toBe('activity.update');expect(c.entityId).toBe(id);expect(c.expectedRevision).toBe(1);expect(c.payload).toEqual({dueDate:tomorrow});expect(c.gikaReschedule).toBeTruthy();ops.push(c.operationId);const r=await route.fetch();expect(r.status()).toBe(200);committed=true;await gate;await route.fulfill({response:r});});
 await ask(page,title);const preview=page.getByRole('group',{name:'Prévia de reagendamento',exact:true});await expect(preview).toContainText(tomorrow.split('-').reverse().join('/'));expect(ops).toHaveLength(0);await expect(preview).toContainText('Horários em America/Sao_Paulo');
 await expect(page.locator('.gika-character')).toHaveAttribute('data-character-state','clarify');
 if(mobile){await expect(page.locator('.gika-character img')).toHaveAttribute('data-static-state','clarify');await expect(page.locator('.gika-character canvas')).toHaveCount(0);}
 const move=preview.getByRole('button',{name:'Mover tarefa',exact:true});const handle=await move.elementHandle();await move.click();await handle!.dispatchEvent('click');await expect.poll(()=>committed).toBe(true);const success=page.getByRole('group',{name:'Tarefa reagendada',exact:true});await expect(success).toHaveCount(0);await expect(page.locator('.gika-character')).toHaveAttribute('data-character-state','thinking');release();await expect(page.locator('.gika-character')).toHaveAttribute('data-character-state','success');await expect(success).toContainText(title);await expect(success).toContainText('Movida para');await expect(page.locator('.gika-character')).toHaveAttribute('data-character-visual-state','idle');if(mobile){await expect(page.locator('.gika-character img')).toHaveAttribute('data-static-state','idle');await expect(page.locator('.gika-character canvas')).toHaveCount(0);}expect(ops).toHaveLength(1);expect(model).toBe(1);expect((await new AxeBuilder({page}).include('.gika-panel').analyze()).violations).toEqual([]);await page.screenshot({path:`/tmp/leve-m4t3-reschedule-${mobile?'mobile-dark':'desktop-light'}.png`});await page.getByRole('button',{name:'Fechar Gika'}).click();await page.goto(`/hoje?dia=${tomorrow}`);await page.reload();await expect(page.locator('.day-activity').filter({hasText:title})).toHaveCount(1);
});
test('M4-T3 cancel preview produces no command',async({page})=>{
 await enter(page);const title='Academia M4T3 cancelar',id=await create(page,title);let writes=0;page.on('request',r=>{if(r.url().endsWith('/api/commands'))writes++;});await page.route('**/api/gika/respond',async route=>route.fulfill({json:await sealedRescheduleFixture(page,route.request().postDataJSON(),descriptor(id,title).rescheduleTask)}));await ask(page,title);await page.getByRole('group',{name:'Prévia de reagendamento'}).getByRole('button',{name:'Cancelar',exact:true}).click();await expect(page.locator('.gika-message.is-assistant')).toContainText('Alteração cancelada.');expect(writes).toBe(0);
});
test('M4-T3 lost actual acknowledgement repeats same operation without new Gemini or revision',async({page})=>{
 await enter(page);const title='Academia M4T3 retry',id=await create(page,title),ops:string[]=[],results:string[]=[];let model=0;await page.route('**/api/gika/respond',async route=>{model++;return route.fulfill({json:await sealedRescheduleFixture(page,route.request().postDataJSON(),descriptor(id,title).rescheduleTask)});});await page.route('**/api/commands',async route=>{const c=route.request().postDataJSON();ops.push(c.operationId);const r=await route.fetch();expect(r.status()).toBe(200);const ack=await r.json();expect(ack.revision).toBe(2);results.push(ack.result);if(ops.length===1)await route.abort('failed');else await route.fulfill({response:r});});await ask(page,title);await page.getByRole('button',{name:'Mover tarefa',exact:true}).click();await expect(page.getByRole('button',{name:'Tentar mover novamente'})).toBeVisible();await expect(page.getByRole('group',{name:'Tarefa reagendada',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Tentar mover novamente'}).click();await expect(page.getByRole('group',{name:'Tarefa reagendada',exact:true})).toContainText(title);expect(ops[0]).toBe(ops[1]);expect(results).toEqual(['applied','alreadyApplied']);expect(model).toBe(1);
});
test('M4-T3 later conventional edit conflicts at original revision and preserves edit',async({page})=>{
 await enter(page);const title='Academia M4T3 conflito',id=await create(page,title);await page.route('**/api/gika/respond',async route=>route.fulfill({json:await sealedRescheduleFixture(page,route.request().postDataJSON(),descriptor(id,title).rescheduleTask)}));await ask(page,title);await expect(page.getByRole('button',{name:'Mover tarefa',exact:true})).toBeVisible();await page.evaluate(async({id,value})=>{const path='/src/platform/api.ts';const {sendCommand}=await import(/* @vite-ignore */path);await sendCommand({command:'activity.update',entityId:id,operationId:crypto.randomUUID(),expectedRevision:1,payload:value});},{id,value:payload(title+' editada')});await page.getByRole('button',{name:'Mover tarefa',exact:true}).click();await expect(page.getByRole('group',{name:'Prévia de reagendamento',exact:true})).toContainText('Essa tarefa mudou antes do reagendamento. Faça o pedido novamente.');await expect(page.getByRole('button',{name:'Tentar mover novamente'})).toHaveCount(0);await expect(page.getByRole('group',{name:'Tarefa reagendada',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Fechar Gika'}).click();await page.goto(`/hoje?dia=${dueDate}`);await expect(page.locator('.day-activity').filter({hasText:title+' editada'})).toHaveCount(1);
});
test('M4-T3 observation partial/ambiguous/no-op never writes',async({page})=>{
 await enter(page);let writes=0,status='partial';page.on('request',r=>{if(r.url().endsWith('/api/commands'))writes++;});await page.route('**/api/gika/respond',route=>route.fulfill({json:{text:'Confira sua agenda.',simulated:false,reads:[],rescheduleResolution:{status,candidates:[]}}}));const q=await ask(page,'Academia');await expect(page.locator('.gika-message.is-assistant')).toHaveCount(1);let count=1;for(status of ['ambiguous','not_found','unchanged','unsupported']){await q.fill('Move Academia para amanhã');await q.press('Enter');await expect(page.locator('.gika-message.is-assistant')).toHaveCount(++count);}expect(writes).toBe(0);await expect(page.getByRole('button',{name:'Mover tarefa',exact:true})).toHaveCount(0);
});
test('M4-T3 logout during resolution discards preview without dispatch',async({page})=>{
 await enter(page);const title='Academia M4T3 logout',id=await create(page,title);let writes=0,finish:(()=>Promise<void>)|undefined;page.on('request',r=>{if(r.url().endsWith('/api/commands')&&r.postDataJSON()?.gikaReschedule)writes++;});await page.route('**/api/gika/respond',async route=>{const json=await sealedRescheduleFixture(page,route.request().postDataJSON(),descriptor(id,title).rescheduleTask);finish=()=>route.fulfill({json}).catch(()=>undefined);});await ask(page,title);await expect.poll(()=>Boolean(finish)).toBe(true);await page.getByRole('button',{name:'Fechar Gika'}).click();await page.getByRole('button',{name:'Sair',exact:true}).click();await finish!();await enter(page);await page.getByRole('button',{name:'Pergunte à Gika'}).click();await expect(page.locator('.gika-message')).toHaveCount(0);expect(writes).toBe(0);
});

test('M5-T2 keyboard cancellation is terminal, focused, no receipt and no reload restoration',async({page})=>{
 await enter(page);const title='Teste Gika confirmação cancelar',id=await create(page,title);let model=0,writes=0,requestId='';
 page.on('request',r=>{if(r.url().endsWith('/api/commands')&&r.method()==='POST')writes++;});
 await page.route('**/api/gika/respond',async route=>{model++;requestId=route.request().postDataJSON().requestId;return route.fulfill({json:await sealedRescheduleFixture(page,route.request().postDataJSON(),descriptor(id,title).rescheduleTask)});});
 await ask(page,title);const card=page.getByRole('group',{name:'Prévia de reagendamento'});await expect(card).toHaveAttribute('data-confirmation-state','awaiting_confirmation');
 const cancel=card.getByRole('button',{name:'Cancelar',exact:true});await cancel.focus();await page.keyboard.press('Enter');await expect(card).toHaveAttribute('data-confirmation-state','cancelled');await expect(card.getByRole('status')).toBeFocused();await expect(card.getByRole('button')).toHaveCount(0);expect(writes).toBe(0);expect(model).toBe(1);
 const receipt=await page.evaluate(async operation=>{const path='/src/platform/api.ts';return (await import(/* @vite-ignore */path)).apiRequest(`/commands/${operation}`);},requestId);expect(receipt).toEqual({result:null});
 await page.reload();await page.getByRole('button',{name:'Pergunte à Gika'}).click();await expect(page.getByRole('group',{name:'Prévia de reagendamento'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Mover tarefa',exact:true})).toHaveCount(0);
});
test('M5-T2 failure before commit never confirms and retries original sealed operation without model',async({page})=>{
 await enter(page);const title='Teste Gika confirmação falha',id=await create(page,title);let model=0;const ops:string[]=[];
 await page.route('**/api/gika/respond',async route=>{model++;return route.fulfill({json:await sealedRescheduleFixture(page,route.request().postDataJSON(),descriptor(id,title).rescheduleTask)});});
 await page.route('**/api/commands',async route=>{ops.push(route.request().postDataJSON().operationId);if(ops.length===1)return route.abort('failed');return route.fulfill({response:await route.fetch()});});
 await ask(page,title);await page.getByRole('button',{name:'Mover tarefa',exact:true}).click();const card=page.getByRole('group',{name:'Prévia de reagendamento'});await expect(card).toHaveAttribute('data-confirmation-state','failed');await expect(page.getByRole('group',{name:'Tarefa reagendada'})).toHaveCount(0);
 await page.getByRole('button',{name:'Tentar mover novamente'}).click();const final=page.getByRole('group',{name:'Tarefa reagendada'});await expect(final).toHaveAttribute('data-confirmation-state','confirmed');await expect(final.getByRole('button')).toHaveCount(0);expect(ops).toHaveLength(2);expect(ops[0]).toBe(ops[1]);expect(model).toBe(1);
});
test('M5-T2 tampered transport target or patch cannot apply a different approved effect',async({page})=>{
 await enter(page);const title='Teste Gika confirmação adulterada',id=await create(page,title),other=await create(page,'Teste Gika vizinha intacta');let model=0;
 await page.route('**/api/gika/respond',async route=>{model++;return route.fulfill({json:await sealedRescheduleFixture(page,route.request().postDataJSON(),descriptor(id,title).rescheduleTask)});});
 await page.route('**/api/commands',async route=>{const c=route.request().postDataJSON();const r=await route.fetch({postData:{...c,entityId:other,payload:{dueDate:tomorrow}}});expect(r.status()).toBe(422);return route.fulfill({response:r});});
 await ask(page,title);await page.getByRole('button',{name:'Mover tarefa',exact:true}).click();const card=page.getByRole('group',{name:'Prévia de reagendamento'});await expect(card).toHaveAttribute('data-confirmation-state','failed');await expect(card.getByRole('button')).toHaveCount(0);expect(model).toBe(1);
 await page.getByRole('button',{name:'Fechar Gika'}).click();await page.goto(`/hoje?dia=${dueDate}`);await expect(page.locator('.day-activity').filter({hasText:title})).toHaveCount(1);await expect(page.locator('.day-activity').filter({hasText:'Teste Gika vizinha intacta'})).toHaveCount(1);
});
test('M5-T2 narrative confirmation and allow/clarify/deny observations never become executable cards',async({page})=>{
 await enter(page);let writes=0,state='allow';page.on('request',r=>{if(r.url().endsWith('/api/commands')&&r.method()==='POST')writes++;});
 await page.route('**/api/gika/respond',route=>route.fulfill({json:state==='allow'?{text:'Confirma?',simulated:false,reads:[]}:{text:'Confira sua agenda.',simulated:false,reads:[],rescheduleResolution:{status:state==='clarify'?'ambiguous':'partial',candidates:[]}}}));
 const q=await ask(page,'Academia');await expect(page.locator('.gika-message.is-assistant')).toHaveCount(1);let count=1;for(state of ['clarify','deny']){await q.fill('Move Academia para amanhã');await q.press('Enter');await expect(page.locator('.gika-message.is-assistant')).toHaveCount(++count);}await expect(page.getByRole('button',{name:'Mover tarefa'})).toHaveCount(0);expect(writes).toBe(0);
});
test('M5-T2 logout after preview removes execution and stale account descriptor cannot dispatch',async({page})=>{
 await enter(page);const title='Teste Gika confirmação logout',id=await create(page,title);let captured:Awaited<ReturnType<typeof sealedRescheduleFixture>>|undefined,input:{requestId:string;text:string}|undefined;let writes=0;
 await page.route('**/api/gika/respond',async route=>{input=route.request().postDataJSON();captured=await sealedRescheduleFixture(page,input!,descriptor(id,title).rescheduleTask);return route.fulfill({json:captured});});
 await ask(page,title);await expect(page.getByRole('button',{name:'Mover tarefa',exact:true})).toBeVisible();page.on('request',r=>{if(r.url().endsWith('/api/commands')&&r.method()==='POST')writes++;});
 const uid=await page.evaluate(async()=>{const path='/src/platform/firebase.ts';return (await import(/* @vite-ignore */path)).firebaseAuth.currentUser.uid as string;});await page.getByRole('button',{name:'Fechar Gika'}).click();await page.getByRole('button',{name:'Sair',exact:true}).click();await expect(page.getByLabel('E-mail')).toBeVisible();
 const code=await page.evaluate(async value=>{const path='/src/features/gika/confirmationBridge.ts';try{await(await import(/* @vite-ignore */path)).confirmGikaAction(value.confirmation,value.input,value.uid,new AbortController().signal);return 'UNEXPECTED_SUCCESS';}catch(error){return (error as {code:string}).code;}},{confirmation:captured!.confirmation,input:input!,uid});expect(code).toBe('AUTH_REQUIRED');expect(writes).toBe(0);
});
