import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { Temporal } from '@js-temporal/polyfill';
const dueDate = Temporal.Now.instant().toZonedDateTimeISO('America/Sao_Paulo').toPlainDate().toString();
async function enter(page: Page) {
  await page.goto('/entrar'); await page.getByLabel('E-mail').fill('leve.local@example.test'); await page.getByLabel('Senha', { exact: true }).fill('leve-local-123'); await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.locator('#page-title')).toHaveText(/Finalize sua agenda|Meu dia/);
  if (await page.getByRole('heading', { name: 'Finalize sua agenda' }).count()) await page.getByRole('button', { name: 'Criar minha agenda' }).click();
  await expect(page.locator('#page-title')).toHaveText('Meu dia'); const skip = page.getByRole('button', { name: 'Pular guia', exact: true }); await skip.waitFor({ state: 'visible', timeout: 3000 }).catch(() => undefined);
  if (await skip.isVisible()) { const ack = page.waitForResponse(r => r.url().endsWith('/api/commands') && r.request().postDataJSON()?.command === 'profile.completeTutorial'); await skip.click(); await ack; }
}
const payload = (title: string) => ({ title, descriptionPlain: 'Nota sintética preservada', categoryId: null, colorHex: '#65A885', estimatedMinutes: 35, reminderSpecs: [], schedule: { type: 'task', dueDate, dueTime: null, timeZone: 'America/Sao_Paulo', disambiguation: 'reject' } });
async function create(page: Page, title: string) { return page.evaluate(async value => {
  const path = '/src/platform/api.ts'; const { sendCommand } = await import(/* @vite-ignore */ path); const id = crypto.randomUUID();
  await sendCommand({ command: 'activity.create', operationId: crypto.randomUUID(), entityId: id, expectedRevision: 0, payload: value }); return id;
}, payload(title)); }
const tomorrow=Temporal.PlainDate.from(dueDate).add({days:1}).toString();
const descriptor=(id:string,title:string,time:string|null=null)=>({text:'Confira a nova data antes de mover a tarefa.',simulated:false,reads:[],rescheduleTask:{id,title,dueDate,dueTime:time,timeZone:'America/Sao_Paulo',revision:1,patch:{dueDate:tomorrow}}});
async function ask(page:Page,title:string){await page.getByRole('button',{name:'Pergunte à Gika'}).click();const q=page.getByRole('textbox',{name:'Pergunte à Gika',exact:true});await q.fill(`Move "${title}" para amanhã`);await q.press('Enter');return q;}
for(const mobile of [false,true])test(`M4-T3 ${mobile?'mobile dark':'desktop light'} preview, double tap, structured result after real ack`,async({page})=>{
 if(mobile){await page.setViewportSize({width:390,height:844});await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});}await enter(page);if(mobile)await page.evaluate(async()=>{const path='/src/platform/theme.ts';(await import(/* @vite-ignore */path)).applyAppearance('dark');});
 const title=`Academia M4T3 ${mobile?'mobile':'desktop'}`,id=await create(page,title);await create(page,title+' outro');let model=0,committed=false;const ops:string[]=[];
 await page.route('**/api/gika/respond',route=>{model++;return route.fulfill({json:descriptor(id,title)});});let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});
 await page.route('**/api/commands',async route=>{const c=route.request().postDataJSON();expect(c.command).toBe('activity.update');expect(c.entityId).toBe(id);expect(c.expectedRevision).toBe(1);expect(c.payload).toEqual({dueDate:tomorrow});expect(c.gikaReschedule).toBeTruthy();ops.push(c.operationId);const r=await route.fetch();expect(r.status()).toBe(200);committed=true;await gate;await route.fulfill({response:r});});
 await ask(page,title);const preview=page.getByRole('group',{name:'Prévia de reagendamento',exact:true});await expect(preview).toContainText(tomorrow.split('-').reverse().join('/'));expect(ops).toHaveLength(0);await expect(preview).toContainText('Horários em America/Sao_Paulo');
 const move=preview.getByRole('button',{name:'Mover tarefa',exact:true});const handle=await move.elementHandle();await move.click();await handle!.dispatchEvent('click');await expect.poll(()=>committed).toBe(true);const success=page.getByRole('group',{name:'Tarefa reagendada',exact:true});await expect(success).toHaveCount(0);release();await expect(success).toContainText(title);await expect(success).toContainText('Movida para');expect(ops).toHaveLength(1);expect(model).toBe(1);expect((await new AxeBuilder({page}).include('.gika-panel').analyze()).violations).toEqual([]);await page.screenshot({path:`/tmp/leve-m4t3-reschedule-${mobile?'mobile-dark':'desktop-light'}.png`});await page.getByRole('button',{name:'Fechar Gika'}).click();await page.goto(`/hoje?dia=${tomorrow}`);await page.reload();await expect(page.locator('.day-activity').filter({hasText:title})).toHaveCount(1);
});
test('M4-T3 cancel preview produces no command',async({page})=>{
 await enter(page);const title='Academia M4T3 cancelar',id=await create(page,title);let writes=0;page.on('request',r=>{if(r.url().endsWith('/api/commands'))writes++;});await page.route('**/api/gika/respond',route=>route.fulfill({json:descriptor(id,title)}));await ask(page,title);await page.getByRole('group',{name:'Prévia de reagendamento'}).getByRole('button',{name:'Cancelar',exact:true}).click();await expect(page.locator('.gika-message.is-assistant')).toContainText('Reagendamento cancelado.');expect(writes).toBe(0);
});
test('M4-T3 lost actual acknowledgement repeats same operation without new Gemini or revision',async({page})=>{
 await enter(page);const title='Academia M4T3 retry',id=await create(page,title),ops:string[]=[],results:string[]=[];let model=0;await page.route('**/api/gika/respond',route=>{model++;return route.fulfill({json:descriptor(id,title)});});await page.route('**/api/commands',async route=>{const c=route.request().postDataJSON();ops.push(c.operationId);const r=await route.fetch();expect(r.status()).toBe(200);const ack=await r.json();expect(ack.revision).toBe(2);results.push(ack.result);if(ops.length===1)await route.abort('failed');else await route.fulfill({response:r});});await ask(page,title);await page.getByRole('button',{name:'Mover tarefa',exact:true}).click();await expect(page.getByRole('button',{name:'Tentar mover novamente'})).toBeVisible();await expect(page.getByRole('group',{name:'Tarefa reagendada',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Tentar mover novamente'}).click();await expect(page.getByRole('group',{name:'Tarefa reagendada',exact:true})).toContainText(title);expect(ops[0]).toBe(ops[1]);expect(results).toEqual(['applied','alreadyApplied']);expect(model).toBe(1);
});
test('M4-T3 later conventional edit conflicts at original revision and preserves edit',async({page})=>{
 await enter(page);const title='Academia M4T3 conflito',id=await create(page,title);await page.route('**/api/gika/respond',route=>route.fulfill({json:descriptor(id,title)}));await ask(page,title);await expect(page.getByRole('button',{name:'Mover tarefa',exact:true})).toBeVisible();await page.evaluate(async({id,value})=>{const path='/src/platform/api.ts';const {sendCommand}=await import(/* @vite-ignore */path);await sendCommand({command:'activity.update',entityId:id,operationId:crypto.randomUUID(),expectedRevision:1,payload:value});},{id,value:payload(title+' editada')});await page.getByRole('button',{name:'Mover tarefa',exact:true}).click();await expect(page.getByRole('group',{name:'Prévia de reagendamento',exact:true})).toContainText('Essa tarefa mudou antes do reagendamento. Faça o pedido novamente.');await expect(page.getByRole('button',{name:'Tentar mover novamente'})).toHaveCount(0);await expect(page.getByRole('group',{name:'Tarefa reagendada',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Fechar Gika'}).click();await page.goto(`/hoje?dia=${dueDate}`);await expect(page.locator('.day-activity').filter({hasText:title+' editada'})).toHaveCount(1);
});
test('M4-T3 observation partial/ambiguous/no-op never writes',async({page})=>{
 await enter(page);let writes=0,status='partial';page.on('request',r=>{if(r.url().endsWith('/api/commands'))writes++;});await page.route('**/api/gika/respond',route=>route.fulfill({json:{text:'Confira sua agenda.',simulated:false,reads:[],rescheduleResolution:{status,candidates:[]}}}));const q=await ask(page,'Academia');await expect(page.locator('.gika-message.is-assistant')).toHaveCount(1);let count=1;for(status of ['ambiguous','not_found','unchanged','unsupported']){await q.fill('Move Academia para amanhã');await q.press('Enter');await expect(page.locator('.gika-message.is-assistant')).toHaveCount(++count);}expect(writes).toBe(0);await expect(page.getByRole('button',{name:'Mover tarefa',exact:true})).toHaveCount(0);
});
test('M4-T3 logout during resolution discards preview without dispatch',async({page})=>{
 await enter(page);const title='Academia M4T3 logout',id=await create(page,title);let writes=0,finish:(()=>Promise<void>)|undefined;page.on('request',r=>{if(r.url().endsWith('/api/commands')&&r.postDataJSON()?.gikaReschedule)writes++;});await page.route('**/api/gika/respond',route=>{finish=()=>route.fulfill({json:descriptor(id,title)}).catch(()=>undefined);});await ask(page,title);await expect.poll(()=>Boolean(finish)).toBe(true);await page.getByRole('button',{name:'Fechar Gika'}).click();await page.getByRole('button',{name:'Sair',exact:true}).click();await finish!();await enter(page);await page.getByRole('button',{name:'Pergunte à Gika'}).click();await expect(page.locator('.gika-message')).toHaveCount(0);expect(writes).toBe(0);
});
