import { test, expect } from '@playwright/test';
import { isolatedTestAccount } from '../helpers/gikaBatch';
import { Temporal } from '@js-temporal/polyfill';
test('M9 launcher leaves logout reachable after scrolling a long agenda', async ({ page }) => {
  const email = await isolatedTestAccount('launcher');
  await page.goto('/entrar'); await page.getByLabel('E-mail').fill(email); await page.getByLabel('Senha', { exact: true }).fill('leve-local-123'); await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.locator('#page-title')).toHaveText(/Finalize sua agenda|Meu dia/);
  if (await page.getByRole('heading', { name: 'Finalize sua agenda' }).count()) await page.getByRole('button', { name: 'Criar minha agenda' }).click();
  await expect(page.locator('#page-title')).toHaveText('Meu dia');
  const skip=page.getByRole('button',{name:'Pular guia',exact:true}); await skip.waitFor({state:'visible',timeout:3000}).catch(()=>undefined);if(await skip.isVisible())await skip.click();
  const today=Temporal.Now.instant().toZonedDateTimeISO('America/Sao_Paulo').toPlainDate().toString();
  await page.evaluate(async dueDate=>{const path='/src/platform/api.ts';const {sendCommand}=await import(/* @vite-ignore */path);for(let index=0;index<26;index++)await sendCommand({command:'activity.create',operationId:crypto.randomUUID(),entityId:crypto.randomUUID(),expectedRevision:0,payload:{title:`Synthetic footer ${index}`,descriptionPlain:'',categoryId:null,colorHex:null,estimatedMinutes:null,reminderSpecs:[],schedule:{type:'task',dueDate,dueTime:null,timeZone:'America/Sao_Paulo',disambiguation:'reject'}}});},today);
  await expect(page.getByRole('heading',{name:'26 tarefas para hoje',exact:true})).toBeVisible();
  await page.route('**/api/gika/respond',()=>{}); await page.getByRole('button',{name:'Pergunte à Gika',exact:true}).click(); const input=page.getByRole('textbox',{name:'Pergunte à Gika',exact:true});await input.fill('Synthetic pending query');await input.press('Enter'); await page.getByRole('button',{name:'Fechar Gika',exact:true}).click();
  const logout=page.getByRole('button',{name:'Sair',exact:true});await logout.scrollIntoViewIfNeeded();
  await expect.poll(() => logout.evaluate(element => { const b = element.getBoundingClientRect(); return !!document.elementFromPoint(b.x + b.width / 2, b.y + b.height / 2)?.closest('.gika-launcher'); })).toBe(false);
  const hit=await logout.evaluate(element=>{const b=element.getBoundingClientRect();return {targetIsLauncher:!!document.elementFromPoint(b.x+b.width/2,b.y+b.height/2)?.closest('.gika-launcher'),top:Math.round(b.top),bottom:Math.round(b.bottom)};});
  console.log(JSON.stringify({stage:'conventional footer hit test',syntheticPending:26,...hit}));expect(hit.targetIsLauncher).toBe(false);
  await logout.click(); await expect(page.getByLabel('E-mail')).toBeVisible();
});

test('M9 launcher leaves short shopping list actions reachable on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'light' });
  const email = await isolatedTestAccount('launcher-shopping');
  await page.goto('/entrar'); await page.getByLabel('E-mail').fill(email); await page.getByLabel('Senha', { exact: true }).fill('leve-local-123'); await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Finalize sua agenda' })).toBeVisible();
  await page.getByRole('button', { name: 'Criar minha agenda' }).click(); await expect(page.locator('#page-title')).toHaveText('Meu dia');
  await page.getByRole('button', { name: 'Pular guia', exact: true }).click();
  await page.getByRole('navigation', { name: 'Principal', exact: true }).getByRole('link', { name: 'Compras', exact: true }).click();
  await page.getByLabel('Nome da lista').fill('Synthetic launcher list'); await page.getByRole('button', { name: 'Criar lista', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synthetic launcher list', exact: true })).toBeVisible();
  await page.getByLabel('Adicionar item', { exact: true }).fill('Synthetic item'); await page.getByRole('button', { name: 'Adicionar item', exact: true }).click();
  await expect(page.getByText('Synthetic item', { exact: true })).toBeVisible();
  await page.goto('/compras');
  const card = page.locator('.shopping-list-card').filter({ hasText: 'Synthetic launcher list' });
  const remove = card.getByRole('button', { name: 'Excluir', exact: true });
  await remove.scrollIntoViewIfNeeded();
  await expect.poll(() => remove.evaluate(element => { const rect = element.getBoundingClientRect(); return !!document.elementFromPoint(rect.x + rect.width / 2, rect.y + rect.height / 2)?.closest('.gika-launcher'); })).toBe(false);
  await remove.click(); await expect(card).toHaveCount(0);
  await expect(page.locator('.gika-panel')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Pergunte à Gika', exact: true })).toBeVisible();
  const gika = page.getByRole('navigation', { name: 'Principal', exact: true }).getByRole('button', { name: 'Pergunte à Gika', exact: true });
  await expect(gika).toHaveCount(1);
  expect(await gika.evaluate(element => getComputedStyle(element).position)).not.toBe('fixed');
  const target = await gika.boundingBox(), avatar = await gika.locator('img').boundingBox();
  expect(target!.width).toBeGreaterThanOrEqual(44); expect(target!.height).toBeGreaterThanOrEqual(44);
  expect(avatar!.width).toBeGreaterThanOrEqual(44); expect(avatar!.width).toBeLessThanOrEqual(52);
  await gika.click(); await expect(page.getByRole('dialog', { name: 'Gika', exact: true })).toBeVisible();
  await expect(page.locator('.gika-panel')).toHaveCount(1);
  await expect(gika).toHaveAttribute('aria-expanded', 'true'); await expect(gika).toHaveAttribute('aria-controls', 'gika-dialog');
  await page.getByRole('button', { name: 'Fechar Gika', exact: true }).click(); await expect(gika).toBeFocused();
  await expect(gika).toHaveAttribute('aria-expanded', 'false');
});
