import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { Temporal } from '@js-temporal/polyfill';
import { isolatedTestAccount } from '../helpers/gikaBatch';

test('repetição anual e personalizada usam modal; avisos ampliados persistem sem horário de aviso na tela', async ({ page }) => {
  const email = await isolatedTestAccount('recurrence-options');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/entrar');
  await page.getByLabel('E-mail').fill(email);
  await page.getByLabel('Senha', { exact: true }).fill('leve-local-123');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('button', { name: 'Criar minha agenda', exact: true }).click();
  await expect(page.locator('#page-title')).toHaveText('Meu dia');
  const skip = page.getByRole('button', { name: 'Pular guia', exact: true });
  await skip.waitFor({ state: 'visible', timeout: 3000 }).catch(() => undefined);
  if (await skip.isVisible()) await skip.click();
  const date = Temporal.Now.plainDateISO('America/Sao_Paulo').add({ days: 10 }).toString();

  for (const frequency of ['yearly', 'custom']) {
    await page.getByRole('button', { name: 'Nova atividade', exact: true }).click();
    await page.getByLabel('Título', { exact: true }).fill(`Rotina ${frequency}`);
    await page.getByLabel('Data', { exact: true }).fill(date);
    await page.locator('.activity-composer .optional-fields > summary').click();
    await expect(page.locator('[name=dayReminderTime]')).toHaveCount(0);
    await expect(page.locator('.activity-composer')).not.toContainText('00:00');
    const trigger = page.getByRole('button', { name: /Repetir atividade/ });
    await trigger.click();
    let dialog = page.getByRole('dialog', { name: 'Repetir atividade', exact: true });
    await expect(dialog.getByRole('button', { name: 'Não se repete', exact: true })).toHaveAttribute('aria-pressed', 'true');
    expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
    await page.screenshot({ path: '/tmp/leve-recurrence-options.png' });
    await page.keyboard.press('Escape');
    await expect(trigger).toBeFocused();
    await trigger.click();
    dialog = page.getByRole('dialog', { name: 'Repetir atividade', exact: true });
    await dialog.getByRole('button', { name: frequency === 'yearly' ? 'Todos os anos' : 'Personalizar…', exact: true }).click();
    await expect(trigger).toBeFocused();
    if (frequency === 'custom') {
      await page.getByLabel('Repetir a cada', { exact: true }).fill('2');
      await page.getByRole('combobox', { name: 'Unidade da repetição', exact: true }).selectOption('weekly');
    }
    await page.getByRole('combobox', { name: 'Termina', exact: true }).selectOption('count');
    await page.getByLabel('Quantidade de ocorrências').fill('3');
    for (let index = 1; index <= 3; index++) await page.getByRole('button', { name: 'Adicionar aviso antecipado', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Adicionar aviso antecipado', exact: true })).toHaveCount(0);
    await page.getByRole('combobox', { name: 'Aviso antecipado 1', exact: true }).selectOption('10');
    await page.getByRole('combobox', { name: 'Aviso antecipado 2', exact: true }).selectOption('10080');
    await page.getByRole('combobox', { name: 'Aviso antecipado 3', exact: true }).selectOption('custom');
    await page.getByRole('combobox', { name: 'Unidade do aviso 3', exact: true }).selectOption('1440');
    await page.getByLabel('Antecedência 3', { exact: true }).fill('3');
    const ack = page.waitForResponse(response => response.url().endsWith('/api/commands') && response.request().postDataJSON()?.command === 'activity.createSeries');
    await page.getByRole('button', { name: 'Adicionar atividade', exact: true }).click();
    const response = await ack;
    expect(response.status()).toBe(200);
    const payload = response.request().postDataJSON().payload;
    expect(payload.recurrence).toMatchObject({ frequency: frequency === 'yearly' ? 'yearly' : 'weekly', interval: frequency === 'yearly' ? 1 : 2, count: 3, until: null });
    expect(payload.activity.reminderSpecs.map((spec: { minutesBefore: number }) => spec.minutesBefore)).toEqual([10, 10080, 4320]);
    expect(payload.activity).not.toHaveProperty('dayReminderTime');
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto(`/hoje?dia=${date}`);
  let deleteCommands = 0;
  page.on('request', request => { if (request.url().endsWith('/api/commands') && request.postDataJSON()?.command === 'activity.trashSeries') deleteCommands++; });
  page.on('dialog', async dialog => { await dialog.dismiss(); throw new Error('A exclusão não deve abrir um aviso JavaScript.'); });
  const deleteSeries = page.getByRole('button', { name: 'Excluir toda a série de Rotina custom', exact: true });
  await deleteSeries.click();
  const confirmation = page.getByRole('dialog', { name: 'Excluir esta série?', exact: true });
  await expect(confirmation).toContainText('inclusive as passadas');
  await expect(confirmation.getByRole('button', { name: 'Cancelar', exact: true })).toBeFocused();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.keyboard.press('Escape');
  await expect(confirmation).toHaveCount(0);
  await expect(deleteSeries).toBeFocused();
  expect(deleteCommands).toBe(0);
  await deleteSeries.click();
  await confirmation.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await expect(confirmation).toHaveCount(0);
  expect(deleteCommands).toBe(0);
  await deleteSeries.click();
  let releaseSeries: () => void = () => undefined;
  const seriesDelay = new Promise<void>(resolve => { releaseSeries = resolve; });
  await page.route('**/api/commands', async route => {
    if (route.request().postDataJSON()?.command !== 'activity.trashSeries') return route.continue();
    await seriesDelay;
    await route.fulfill({ status: 503, json: { code: 'SERVICE_RESTRICTED', message: 'Falha controlada ao excluir série.' } });
  });
  await confirmation.getByRole('button', { name: 'Excluir série', exact: true }).click();
  await expect(confirmation).toHaveCount(0);
  await expect(deleteSeries).toHaveCount(0);
  await expect(page.getByText('Excluindo série…', { exact: true })).toBeVisible();
  releaseSeries();
  await expect(deleteSeries).toBeVisible();
  await expect(page.getByText('Falha controlada ao excluir série.', { exact: true })).toBeVisible();
  await page.unroute('**/api/commands');
  await deleteSeries.click();
  const deletion = page.waitForResponse(response => response.url().endsWith('/api/commands') && response.request().postDataJSON()?.command === 'activity.trashSeries');
  await confirmation.getByRole('button', { name: 'Excluir série', exact: true }).click();
  expect((await deletion).status()).toBe(200);
  await expect(confirmation).toHaveCount(0);
  await expect(deleteSeries).toHaveCount(0);
  expect(deleteCommands).toBe(2);
  await page.goto('/lixeira');
  await expect(page.getByText('1 item na lixeira', { exact: true })).toBeVisible();
  const group = page.locator('.trash-list > li');
  await expect(group).toHaveCount(1);
  await expect(group).toContainText('3 ocorrências removidas');
  await expect(group.getByRole('button', { name: /^Restaurar / })).toHaveCount(0);
  await group.locator('summary').click();
  await expect(group.getByRole('button', { name: /^Restaurar / })).toHaveCount(3);
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  let release: () => void = () => undefined;
  const delay = new Promise<void>(resolve => { release = resolve; });
  await page.route('**/api/commands', async route => {
    if (route.request().postDataJSON()?.command !== 'trash.empty') return route.continue();
    await delay;
    await route.fulfill({ status: 503, json: { code: 'SERVICE_RESTRICTED', message: 'Falha controlada de exclusão.' } });
  });
  await page.getByRole('button', { name: 'Excluir tudo', exact: true }).click();
  await page.getByRole('dialog', { name: 'Excluir tudo da lixeira', exact: true }).getByRole('button', { name: 'Excluir definitivamente', exact: true }).click();
  await expect(group).toHaveCount(0);
  await expect(page.getByText('Lixeira esvaziada.', { exact: true })).toHaveCount(0);
  release();
  await expect(page.getByText(/A exclusão não terminou/)).toBeVisible();
  await expect(group).toHaveCount(1);
  await page.unroute('**/api/commands');
  await page.getByRole('button', { name: 'Excluir tudo', exact: true }).click();
  const cleared = page.waitForResponse(response => response.url().endsWith('/api/commands') && response.request().postDataJSON()?.command === 'trash.empty');
  await page.getByRole('dialog', { name: 'Excluir tudo da lixeira', exact: true }).getByRole('button', { name: 'Excluir definitivamente', exact: true }).click();
  expect((await cleared).status()).toBe(200);
  await expect(page.getByText('Lixeira esvaziada.', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText('A lixeira está vazia.', { exact: true })).toBeVisible();
});
