import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('tutorial, cores persistentes, unidade condicional e lixeira móvel', async ({ page }) => {
  test.setTimeout(150_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const title = `Atividade rosa ${Date.now()}`;
  await page.goto('/entrar');
  await page.getByLabel('E-mail').fill('leve.local@example.test');
  await page.getByLabel('Senha', { exact: true }).fill('leve-local-123');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Finalize sua agenda|Meu dia/ })).toBeVisible();
  if (await page.getByRole('heading', { name: 'Finalize sua agenda' }).count()) await page.getByRole('button', { name: 'Criar minha agenda' }).click();
  await expect(page).toHaveURL(/\/hoje$/);
  if (await page.getByRole('button', { name: 'Pular tutorial' }).isVisible()) await page.getByRole('button', { name: 'Pular tutorial' }).click();
  await page.goto('/configuracoes');
  await page.getByRole('button', { name: 'Ver tutorial novamente' }).click();
  const tutorial = page.getByRole('dialog', { name: 'Tutorial do Leve' });
  await expect(tutorial).toBeVisible();
  await tutorial.getByRole('button', { name: 'Próximo' }).click();
  await expect(page.locator('.activity-composer')).toHaveClass(/tutorial-highlight/);
  await tutorial.getByRole('button', { name: 'Próximo' }).click();
  await expect(page.locator('.calendar-panel')).toHaveClass(/tutorial-highlight/);
  await tutorial.getByRole('button', { name: 'Próximo' }).click();
  await expect(tutorial).toContainText('Lembretes neste aparelho');
  await tutorial.getByRole('button', { name: 'Próximo' }).click();
  await tutorial.getByRole('button', { name: 'Concluir tutorial' }).click();
  await expect(tutorial).not.toBeVisible();
  await page.reload(); await expect(page.getByRole('heading', { name: 'Compras', exact: true })).toBeVisible();
  await expect(tutorial).not.toBeVisible();
  await page.getByRole('link', { name: 'Meu dia', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: /Nova atividade/ }).click();
  await expect(page.getByLabel('Título', { exact: true })).toBeFocused();
  await expect(page.locator('.activity-composer')).toBeInViewport();
  await page.getByLabel('Título', { exact: true }).fill(title);
  await page.getByRole('radio', { name: 'Rosa', exact: true }).check();
  await page.locator('.activity-composer').getByRole('button', { name: 'Adicionar atividade', exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toBeVisible();
  await page.reload(); await expect(page.getByText(title, { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Calendário', exact: true }).click();
  await expect(page.locator('.calendar-agenda')).toContainText(title);
  await expect(page.locator('.calendar-agenda')).toContainText('Rosa');
  expect(await page.locator('.calendar-colors > span').evaluateAll(elements => elements.some(element => getComputedStyle(element).backgroundColor === 'rgb(206, 146, 165)'))).toBe(true);
  await page.screenshot({ path: 'docs/evidence/v2-calendar-390.png', fullPage: true });
  await page.getByRole('link', { name: 'Compras', exact: true }).click();
  const list = `Unidades ${Date.now()}`;
  await page.getByLabel('Nome da lista').fill(list); await page.getByRole('button', { name: 'Criar lista', exact: true }).click();
  await page.getByRole('link').filter({ hasText: list }).click();
  await expect(page.getByLabel('Qual unidade?')).toHaveCount(0);
  await page.getByLabel('Unidade', { exact: true }).selectOption('outra');
  await expect(page.getByLabel('Qual unidade?')).toBeVisible();
  await page.getByLabel('Qual unidade?').fill('caixa');
  await page.getByLabel('Unidade', { exact: true }).selectOption('kg');
  await expect(page.getByLabel('Qual unidade?')).toHaveCount(0);
  await page.getByLabel('Adicionar item', { exact: true }).fill('Nome muito comprido de um item de compras para testar a lixeira');
  await page.getByRole('button', { name: 'Adicionar item', exact: true }).click();
  await page.locator('.shopping-item').getByRole('button', { name: /^Excluir / }).click();
  await page.getByRole('link', { name: 'Lixeira', exact: true }).click();
  await expect(page.locator('.trash-list')).toContainText('Nome muito comprido');
  await page.setViewportSize({ width: 320, height: 720 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.locator('.trash-list strong').filter({ hasText: 'Nome muito comprido' })).toHaveCSS('white-space', 'nowrap');
  await page.screenshot({ path: 'docs/evidence/v2-trash-320.png', fullPage: true });
  await page.getByRole('button', { name: 'Excluir tudo', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Manter na lixeira', exact: true }).click();
  await expect(page.locator('.trash-list')).toContainText('Nome muito comprido');
  await page.getByRole('button', { name: 'Excluir tudo', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Excluir definitivamente', exact: true }).click();
  await expect(page.getByText('Lixeira esvaziada.')).toBeVisible();
  await page.reload(); await expect(page.getByText('A lixeira está vazia.')).toBeVisible();
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()).violations).toEqual([]);
  expect(errors).toEqual([]);
});
