import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('cronômetro acompanha a navegação, pausa e retoma sem perder o tempo', async ({ page }) => {
  test.setTimeout(120_000);
  await page.goto('/entrar');
  await page.getByLabel('E-mail').fill('leve.local@example.test');
  await page.getByLabel('Senha', { exact: true }).fill('leve-local-123');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Finalize sua agenda|Meu dia/ })).toBeVisible();
  if (await page.getByRole('heading', { name: 'Finalize sua agenda' }).count()) await page.getByRole('button', { name: 'Criar minha agenda' }).click();
  await expect(page.locator('#page-title')).toHaveText('Meu dia');
  if (await page.getByRole('button', { name: 'Pular guia' }).isVisible()) await page.getByRole('button', { name: 'Pular guia' }).click();
  await page.getByRole('button', { name: 'Nova atividade', exact: true }).click();
  const title = `Sessão ${Date.now()}`;
  await page.getByLabel('Título', { exact: true }).fill(title);
  await page.locator('.activity-composer').getByRole('button', { name: 'Adicionar atividade', exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toBeVisible({ timeout: 25_000 });
  await page.getByText(title, { exact: true }).click();
  await page.getByRole('button', { name: 'Iniciar', exact: true }).click();
  await expect(page.locator('.timer-panel')).toContainText('Em andamento');
  await page.getByRole('link', { name: 'Notas', exact: true }).click();
  const timer = page.getByRole('complementary', { name: `Cronômetro de ${title}`, exact: true });
  await expect(timer).toBeVisible();
  await expect(timer).toContainText(title);
  expect((await new AxeBuilder({ page }).include('.active-timer-bar').withTags(['wcag2a', 'wcag2aa']).analyze()).violations).toEqual([]);
  await page.screenshot({ path: 'docs/evidence/timer-floating-desktop.png', fullPage: true });
  await timer.getByRole('button', { name: 'Pausar cronômetro' }).click();
  await expect(timer).toContainText('Cronômetro pausado');
  const pausedTime = await timer.locator('time').textContent();
  await page.reload();
  const restoredTimer = page.getByRole('complementary', { name: `Cronômetro de ${title}`, exact: true });
  await expect(restoredTimer.locator('time')).toHaveText(pausedTime ?? '');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect((await new AxeBuilder({ page }).include('.active-timer-bar').withTags(['wcag2a', 'wcag2aa']).analyze()).violations).toEqual([]);
  await page.screenshot({ path: 'docs/evidence/timer-floating-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });
  await restoredTimer.getByRole('button', { name: 'Retomar cronômetro' }).click();
  await restoredTimer.getByRole('link', { name: `Abrir cronômetro de ${title}` }).click();
  await expect(page.locator('#cronometro')).toBeInViewport();
  await page.getByRole('button', { name: 'Encerrar', exact: true }).click();
  await page.getByLabel('Tempo manual').fill('2');
  await page.locator('.manual-time').getByRole('button', { name: 'Registrar', exact: true }).click();
  await expect(page.locator('.time-history')).toContainText('Manual');
  await expect(page.getByLabel('Tempo manual')).toHaveValue('');
  await expect(page.locator('.time-history li')).toHaveCount(2);
  await page.reload();
  await expect(page.locator('.time-history li')).toHaveCount(2);
});

test('atalho do Meu dia abre diretamente o cronômetro no celular', async ({ page }) => {
  test.setTimeout(120_000);
  await page.goto('/entrar');
  await page.getByLabel('E-mail').fill('leve.local@example.test');
  await page.getByLabel('Senha', { exact: true }).fill('leve-local-123');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Finalize sua agenda|Meu dia/ })).toBeVisible();
  if (await page.getByRole('heading', { name: 'Finalize sua agenda' }).count()) await page.getByRole('button', { name: 'Criar minha agenda' }).click();
  await expect(page.locator('#page-title')).toHaveText('Meu dia');
  if (await page.getByRole('button', { name: 'Pular guia' }).isVisible()) await page.getByRole('button', { name: 'Pular guia' }).click();
  await page.getByRole('button', { name: 'Nova atividade', exact: true }).click();
  const title = `Atalho do cronômetro ${Date.now()}`;
  await page.getByLabel('Título', { exact: true }).fill(title);
  await page.locator('.activity-composer').getByRole('button', { name: 'Adicionar atividade', exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toBeVisible({ timeout: 25_000 });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('listitem', { name: title }).getByRole('link', { name: `Abrir cronômetro de ${title}` }).click();
  await expect(page).toHaveURL(/#cronometro$/);
  await expect(page.locator('#cronometro')).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'docs/evidence/timer-detail-mobile.png', fullPage: true });
});
