import { expect, test } from '@playwright/test';

test('cronômetro explícito, conclusão e registro manual persistem após recarregar', async ({ page }) => {
  test.setTimeout(120_000);
  await page.goto('/entrar');
  await page.getByLabel('E-mail').fill('leve.local@example.test');
  await page.getByLabel('Senha', { exact: true }).fill('leve-local-123');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.locator('#page-title')).toHaveText('Meu dia');
  if (await page.getByRole('button', { name: 'Pular tutorial' }).isVisible()) await page.getByRole('button', { name: 'Pular tutorial' }).click();
  await page.getByRole('button', { name: 'Nova atividade', exact: true }).click();
  const title = `Sessão ${Date.now()}`;
  await page.getByLabel('Título', { exact: true }).fill(title);
  await page.locator('.activity-composer').getByRole('button', { name: 'Adicionar atividade', exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toBeVisible({ timeout: 25_000 });
  await page.getByText(title, { exact: true }).click();
  await expect(page.locator('.timer-display')).toHaveText('00:00:00');
  await page.getByRole('button', { name: 'Iniciar cronômetro' }).click();
  await page.clock.install();
  await page.clock.fastForward(35_000);
  await expect(page.locator('.timer-display')).toHaveText('00:00:35');
  await page.getByRole('button', { name: 'Parar cronômetro' }).click();
  await expect(page.locator('.time-history')).toContainText('Cronômetro');
  await page.getByRole('button', { name: 'Finalizar' }).click();
  await page.getByRole('button', { name: 'Concluir', exact: true }).click();
  await page.getByText('Adicionar tempo manualmente').click();
  await page.getByLabel('Tempo em minutos').fill('2');
  await page.locator('.manual-time').getByRole('button', { name: 'Adicionar', exact: true }).click();
  await expect(page.locator('.time-history')).toContainText('Manual');
  await expect(page.getByLabel('Tempo em minutos')).toHaveValue('');
  await expect(page.locator('.time-history li')).toHaveCount(2);
  await page.reload();
  await expect(page.locator('.time-history li')).toHaveCount(2);
});

test('cronômetro continua contando fora do detalhe da atividade', async ({ page }) => {
  test.setTimeout(120_000);
  await page.goto('/entrar');
  await page.getByLabel('E-mail').fill('leve.local@example.test');
  await page.getByLabel('Senha', { exact: true }).fill('leve-local-123');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.locator('#page-title')).toHaveText('Meu dia');
  await page.getByRole('button', { name: 'Nova atividade', exact: true }).click();
  const title = `Cronômetro persistente ${Date.now()}`;
  await page.getByLabel('Título', { exact: true }).fill(title);
  await page.locator('.activity-composer').getByRole('button', { name: 'Adicionar atividade', exact: true }).click();
  await expect(page.getByText(title, { exact: true })).toBeVisible({ timeout: 25_000 });
  await page.getByText(title, { exact: true }).click();
  await page.getByRole('button', { name: 'Iniciar cronômetro' }).click();
  await page.clock.install();
  await page.clock.fastForward(35_000);
  await page.getByRole('link', { name: 'Notas', exact: true }).click();
  await page.clock.fastForward(5_000);
  await page.getByRole('link', { name: 'Meu dia', exact: true }).click();
  await page.getByText(title, { exact: true }).click();
  await expect(page.locator('.timer-display')).toHaveText('00:00:40');
  await page.getByRole('button', { name: 'Finalizar' }).click();
  await expect(page.locator('.time-history')).toContainText('Cronômetro');
});
