import type { OrganizationPreview } from '../../../../../packages/domain/src/gikaOrganization';
import type { BatchConfirmation } from '../../../../../packages/domain/src/gikaBatch';
import type { RecurrenceChoice, RecurrenceConfirmation } from '../../../../../packages/domain/src/gikaRecurrence';
import type { GikaConfirmation } from '../../../../../packages/domain/src/gikaConfirmation';
import type { RescheduleDescriptor,RescheduleResolution } from '../../../../../packages/domain/src/gikaReschedule';
import type { UpdatedTask, UpdateResolution } from '../../../../../packages/domain/src/gikaUpdate';
import type { CompletedTask, CompletionResolution } from '../../../../../packages/domain/src/gikaCompletion';
import type { CreationUndoContext } from '../../../../../packages/domain/src/gikaUndo';
import type { GikaRequest, GikaResponse, ReadResult, CreatedTask } from '../../../../../packages/domain/src/gika';
export { GIKA_MAX_INPUT, GIKA_MAX_MESSAGES, GIKA_MAX_REQUEST_BYTES, gikaRequestSchema, gikaResponseSchema } from '../../../../../packages/domain/src/gika';
export type { GikaRequest, GikaResponse };
export type GikaAdapter = (request: GikaRequest, signal: AbortSignal) => Promise<GikaResponse>;
export type GikaMessage = { id: string; role: 'user' | 'assistant'; intent?: 'conversation' | 'agenda_query' | 'agenda_action'; text: string; simulated?: boolean; preview?: 'organize-demo'; reads?: ReadResult[]; organizationPreview?: OrganizationPreview; createdTask?: CreatedTask; completedTask?: CompletedTask; completionResolution?: CompletionResolution; updatedTask?: UpdatedTask; updateResolution?: UpdateResolution; rescheduleTask?: RescheduleDescriptor; confirmation?: GikaConfirmation; rescheduleResolution?: RescheduleResolution; batchConfirmation?: BatchConfirmation; recurrenceChoice?: RecurrenceChoice; recurrenceConfirmation?: RecurrenceConfirmation; rescheduleContext?: {uid:string;request:GikaRequest}; creationUndo?: CreationUndoContext };
